### ISSUE TITLE
Is it still minimal?

### ISSUE THREAD

**Issue by chrollorifat** [borttappat/dotfiles#1]
Bro, I came here from the past. I wanna use your setup. I   would like to know how much is the initial download/installation size during the rebuild?

**Comment by borttappat** [comment]
Hey!
Just set up a fresh install in a vm and a default install ends up at around 17 GB with about 1200 packages.

If you want a more slim system you can just remove or comment out packages in /etc/nixos/packages.nix.

I'll update the guide for installing in the README.

**Comment by borttappat** [comment]
README updated, I'm closing the issue. Feel free to open a new one if questions remain!
